Repository hang-log-design-system/design-system, pull requests merged in 2023-07, with the labels that each got.

#1 Select, Badge 컴포넌트 추가
  .storybook/main.ts
  src/assets/svg/search-icon.svg
  src/components/Badge/Badge.style.ts
  src/components/Badge/Badge.tsx
  src/components/Label/Label.style.ts
  src/components/Label/Label.tsx
  src/components/Select/Select.style.ts
  src/components/Select/Select.tsx
  src/components/Spinner/Spinner.style.ts
  src/components/Spinner/Spinner.tsx
  src/components/SupportingText/SupportingText.style.ts
  src/components/SupportingText/SupportingText.tsx
  src/stories/Badge.stories.tsx
  src/stories/Select.stories.tsx
  src/stories/styles.ts
Labels: ✨ Feature

#2 Checkbox, Tab, Tabs, ToggleGroup, Toggle 컴포넌트 추가
  src/assets/svg/checked-icon.svg
  src/assets/svg/unchecked-icon.svg
  src/components/Checkbox/Checkbox.style.ts
  src/components/Checkbox/Checkbox.tsx
  src/components/Tab/Tab.style.ts
  src/components/Tab/Tab.tsx
  src/components/Tabs/Tabs.style.ts
  src/components/Tabs/Tabs.tsx
  src/components/Toggle/Toggle.style.ts
  src/components/Toggle/Toggle.tsx
  src/components/ToggleGroup/ToggleGroup.style.ts
  src/components/ToggleGroup/ToggleGroup.tsx
  src/stories/Checkbox.stories.tsx
  src/stories/Tabs.stories.tsx
  src/stories/ToggleGroup.stories.tsx
Labels: ✨ Feature

#6 컴포넌트 정리 및 버그 수정
  src/components/Divider/Divider.tsx
  src/components/Heading/Heading.tsx
  src/components/Input/Input.style.ts
  src/components/Label/Label.tsx
  src/components/Text/Text.tsx
  src/components/Textarea/Textarea.style.ts
  src/stories/styles.ts
  src/styles/GlobalStyle.ts
Labels: 🔨 Refactor

#3 FloatingButton, Skeleton, RadioButton 구현
  src/assets/svg/add-icon.svg
  src/components/FloatingButton/FloatingButton.style.ts
  src/components/FloatingButton/FloatingButton.tsx
  src/components/RadioButton/RadioButton.style.ts
  src/components/RadioButton/RadioButton.tsx
  src/components/Skeleton/Skeleton.style.ts
  src/components/Skeleton/Skeleton.tsx
  src/stories/FloatingButton.stories.tsx
  src/stories/RadioButton.stories.tsx
  src/stories/Skeleton.stories.tsx
Labels: ✨ Feature

#19 npm 배포 설정 추가
  .npmignore
  README.md
  package-lock.json
  package.json
  src/components/Checkbox/Checkbox.tsx
  src/components/RadioButton/RadioButton.tsx
  src/index.tsx
  src/styles/GlobalStyle.ts
  src/styles/Theme.ts
  tsconfig.json
Labels: 🌏 Environment

#15 Toast 컴포넌트 구현
  src/HangLogProvider.tsx
  src/assets/svg/check-circle-icon.svg
  src/assets/svg/close-icon.svg
  src/components/Toast/Toast.style.ts
  src/components/Toast/Toast.tsx
  src/components/ToastContainer/ToastContainer.style.ts
  src/components/ToastContainer/ToastContainer.tsx
  src/constants/index.ts
  src/stories/Toast.stories.tsx
  src/styles/Theme.ts
  src/styles/animation/index.ts
Labels: ✨ Feature

#16 Date Range Picker랑 Calendar 컴포넌트 구현
  .storybook/main.ts
  src/assets/svg/left-icon.svg
  src/assets/svg/right-icon.svg
  src/components/Calendar/Calendar.style.ts
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/Day/Day.style.ts
  src/components/Calendar/Day/Day.tsx
  src/components/DateRangePicker/DateRangePicker.style.ts
  src/components/DateRangePicker/DateRangePicker.tsx
  src/constants/index.ts
  src/hooks/useCalendar.ts
  src/hooks/useDateRangePicker.ts
  src/stories/Calendar.stories.tsx
  src/stories/DateRangePicker.stories.tsx
  src/stories/Day.stories.tsx
  src/types/date.ts
  src/utils/date.ts
  tsconfig.json
  webpack.config.js
Labels: ✨ Feature

#18 Modal 컴포넌트 구현
  src/assets/svg/modal-sample.svg
  src/components/Modal/Modal.style.ts
  src/components/Modal/Modal.tsx
  src/stories/Modal.stories.tsx
  src/styles/Theme.ts
Labels: ✨ Feature

#21 Box, Center, Flex 컴포넌트 생성
  src/components/Box/Box.style.ts
  src/components/Box/Box.tsx
  src/components/Center/Center.style.ts
  src/components/Center/Center.tsx
  src/components/Flex/Flex.style.ts
  src/components/Flex/Flex.tsx
  src/stories/Box.stories.tsx
  src/stories/Center.stories.tsx
  src/stories/Flex.stories.tsx
Labels: ✨ Feature

#20 StarRating 컴포넌트 추가
  .storybook/main.ts
  package-lock.json
  package.json
  src/assets/svg/empty-star.svg
  src/assets/svg/filled-star.svg
  src/assets/svg/half-empty-left-star.svg
  src/assets/svg/half-empty-right-star.svg
  src/assets/svg/half-filled-left-star.svg
  src/assets/svg/half-filled-right-star.svg
  src/components/StarRating/StarRating.style.ts
  src/components/StarRating/StarRating.tsx
  src/components/StarRating/useStarRating.ts
  src/stories/StarRating.stories.ts
  webpack.config.js
Labels: ✨ Feature

#24 스토리북 chromatic 자동 배포 기능 추가
  .github/workflows/chromatic.yml
  .gitignore
  package-lock.json
  package.json
Labels: 🌏 Environment, ✨ Feature

#22 Menu 컴포넌트 구현
  src/components/Menu/Menu.style.ts
  src/components/Menu/Menu.tsx
  src/components/MenuItem/MenuItem.style.ts
  src/components/MenuItem/MenuItem.tsx
  src/components/MenuList/MenuList.style.ts
  src/components/MenuList/MenuList.tsx
  src/stories/Menu.stories.tsx
  src/styles/Theme.ts
Labels: ✨ Feature

#25 npm 배포
  README.md
  package-lock.json
  package.json
  src/components/Box/Box.tsx
  src/components/Calendar/Day/Day.tsx
  src/components/Flex/Flex.tsx
  src/components/Menu/Menu.tsx
  src/components/StarRating/StarRating.tsx
  src/hooks/useStarRating.ts
  src/index.tsx
  src/styles/Theme.ts
Labels: 🌏 Environment

#33 svg 업로드 버그 관련 웹팩 수정
  webpack.config.js
Labels: 🐞 Bug

#31 Calendar & DateRangePicker 버그 수정
  src/components/Calendar/Calendar.style.ts
Labels: 🐞 Bug

#36 StarRating 버그수정 및 기능 추가
  src/components/StarRating/StarRating.tsx
  src/hooks/useStarRating.ts
  src/stories/StarRating.stories.tsx
Labels: 🐞 Bug, ✨ Feature

#34 RadioButton 첫번째 옵션 선택된채로 랜더링 되게 수정
  src/components/MenuItem/MenuItem.tsx
  src/components/RadioButton/RadioButton.tsx
  src/stories/Menu.stories.tsx
Labels: 🐞 Bug

#35 열고 닫고 토글할 수 있는 로직 훅으로 생성(useOverlay)
  src/hooks/useOverlay.ts
  src/index.tsx
  src/stories/Menu.stories.tsx
  src/stories/Modal.stories.tsx
  src/stories/Toast.stories.tsx
Labels: ✨ Feature

#38 npm 배포 v1.1.1
  package-lock.json
  package.json
  src/index.tsx
Labels: 🌏 Environment

#41 MenuItem children받도록 수정, hovert시 트렌지션
  src/components/MenuItem/MenuItem.style.ts
  src/components/MenuItem/MenuItem.tsx
  src/stories/Menu.stories.tsx
Labels: 🔨 Refactor

#42 Flex, Center, Box 컴포넌트 고도화
  src/components/Box/Box.style.ts
  src/components/Box/Box.tsx
  src/components/Center/Center.tsx
  src/components/Flex/Flex.style.ts
  src/components/Flex/Flex.tsx
  src/components/Tabs/Tabs.style.ts
  src/index.tsx
Labels: 🔨 Refactor

#44 StarRating -> StarRatingInput 컴포넌트 네이밍 수정
  src/components/StarRatingInput/StarRatingInput.style.ts
  src/components/StarRatingInput/StarRatingInput.tsx
  src/stories/StarRatingInput.stories.tsx
Labels: 🔨 Refactor

#45 npm 배포 v1.1.2
  README.md
  package-lock.json
  package.json
  src/index.tsx
Labels: 🌏 Environment

#46 Box, Flex 컴포넌트 width, height, margin, padding 기본값 제거
  src/components/Box/Box.style.ts
  src/components/Flex/Flex.style.ts
Labels: 🔨 Refactor

#49 DateRangePicker 버그 수정
  src/components/DateRangePicker/DateRangePicker.tsx
  src/hooks/useDateRangePicker.ts
  src/stories/DateRangePicker.stories.tsx
Labels: 🐞 Bug

#52 ImageCarousel 컴포넌트 구현
  src/components/Badge/Badge.style.ts
  src/components/ImageCarousel/ImageCarousel.style.ts
  src/components/ImageCarousel/ImageCarousel.tsx
  src/hooks/useImageCarousel.ts
  src/stories/ImageCarousel.stories.tsx
  src/utils/number.ts
Labels: ✨ Feature

#58 Tab 컴포넌트 수정
  src/components/Tab/Tab.style.ts
Labels: 🔨 Refactor

#65 Tabs, ToggleGroup 컴포넌트 수정
  src/components/Tabs/Tabs.tsx
  src/components/ToggleGroup/ToggleGroup.tsx
Labels: 🔨 Refactor

#67 FloatingButton 컴포넌트 수정
  src/components/FloatingButton/FloatingButton.style.ts
Labels: 🔨 Refactor

#69 feat: Toggle, Tabs 컴포넌트 사용 Hook 추가
  src/components/Tab/Tab.tsx
  src/components/Tabs/Tabs.tsx
  src/components/Toggle/Toggle.tsx
  src/components/ToggleGroup/ToggleGroup.tsx
  src/hooks/useSelect.ts
  src/stories/Tabs.stories.tsx
  src/stories/ToggleGroup.stories.tsx
Labels: 🔨 Refactor, ✨ Feature

#70 fix: 스토리북 Tab 컴포넌트 동작 오류 해결
  src/stories/Tabs.stories.tsx
Labels: 🐞 Bug, 🔨 Refactor

#71 npm v1.1.8 배포
  README.md
  package-lock.json
  package.json
  src/stories/Tabs.stories.tsx
Labels: 🔨 Refactor, ✨ Feature

#74 ToggleGroup, Tabs 컴포넌트 버그 및 useSelect 커스텀 훅 수정
  src/components/Tab/Tab.style.ts
  src/components/Tab/Tab.tsx
  src/components/Tabs/Tabs.style.ts
  src/components/Tabs/Tabs.tsx
  src/components/Toggle/Toggle.style.ts
  src/components/Toggle/Toggle.tsx
  src/components/ToggleGroup/ToggleGroup.style.ts
  src/components/ToggleGroup/ToggleGroup.tsx
  src/hooks/useSelect.ts
  src/stories/Tabs.stories.tsx
  src/stories/ToggleGroup.stories.tsx
Labels: 🐞 Bug, 🔨 Refactor

#75 npm v1.1.10 배포
  README.md
  package-lock.json
  package.json
Labels: 🌏 Environment

#76 npm v1.1.11 배포
  package-lock.json
  package.json
  src/components/Tabs/Tabs.tsx
  src/components/ToggleGroup/ToggleGroup.tsx
  src/hooks/useSelect.ts
  src/hooks/useStarRatingInput.ts
  src/index.tsx
  src/stories/StarRatingInput.stories.tsx
  src/stories/Tabs.stories.tsx
  src/stories/ToggleGroup.stories.tsx
Labels: 🐞 Bug, 🌏 Environment

#82 npm v1.1.13 배포
  README.md
  package-lock.json
  package.json
Labels: ✨ Feature

#83 npm v1.1.14 배포
  package-lock.json
  package.json
  src/index.tsx
Labels: ✨ Feature

#93 StarRatingInput 컴포넌트 수정
  src/components/StarRatingInput/StarRatingInput.style.ts
  src/components/StarRatingInput/StarRatingInput.tsx
  src/stories/StarRatingInput.stories.tsx
Labels: 🔨 Refactor

#94 Modal 컴포넌트 수정
  src/components/Modal/Modal.style.ts
Labels: 🔨 Refactor

#95 Input, Textarea 컴포넌트 수정
  src/components/Input/Input.style.ts
  src/components/Textarea/Textarea.style.ts
Labels: 🔨 Refactor

#103 npm v1.1.19 배포
  README.md
  package-lock.json
  package.json
Labels: 🌏 Environment

#104 npm v1.1.20 배포
  package-lock.json
  package.json
  src/hooks/useStarRatingInput.ts
  src/index.tsx
Labels: 🌏 Environment

#106 npm v1.1.25 배포
  package-lock.json
  package.json
  src/components/ImageCarousel/ImageCarousel.style.ts
  src/components/Modal/Modal.tsx
  src/components/RadioButton/RadioButton.tsx
Labels: 🌏 Environment, 🔨 Refactor

#108 Tab & MenuList 컴포넌트 버그 수정
  src/components/MenuList/MenuList.style.ts
  src/components/Tab/Tab.style.ts
Labels: 🐞 Bug

#109 npm v1.1.26 배포
  README.md
  package-lock.json
  package.json
Labels: 🌏 Environment

#111 컴포넌트 버그 수정
  src/components/ImageUploadInput/ImageUploadInput.style.ts
  src/components/ImageUploadInput/ImageUploadInput.tsx
  src/components/Modal/Modal.style.ts
Labels: 🐞 Bug

#112 npm v1.2.0 배포
  README.md
  package-lock.json
  package.json
Labels: 🌏 Environment

#116 Layout 컴포넌트들 수정
  src/components/Box/Box.tsx
  src/components/Center/Center.tsx
  src/components/Flex/Flex.tsx
  src/types/index.ts
Labels: 🔨 Refactor

#117 DateRangePicker 컴포넌트 수정
  src/components/Calendar/Day/Day.style.ts
  src/components/Calendar/Day/Day.tsx
  src/components/DateRangePicker/DateRangePicker.style.ts
  src/types/index.ts
Labels: 🔨 Refactor

#118 Toggle, Tab 관련 컴포넌트 리팩토링
  src/components/Tab/Tab.style.ts
  src/components/Tab/Tab.tsx
  src/components/Tabs/Tabs.style.ts
  src/components/Tabs/Tabs.tsx
  src/components/Toggle/Toggle.style.ts
  src/components/Toggle/Toggle.tsx
  src/components/ToggleGroup/ToggleGroup.style.ts
  src/components/ToggleGroup/ToggleGroup.tsx
Labels: 🐞 Bug, 🔨 Refactor

#119 npm v1.2.1 배포
  README.md
  package-lock.json
  package.json
  src/components/Center/Center.tsx
  src/components/ImageUploadInput/ImageUploadInput.style.ts
Labels: 🌏 Environment

#123 MenuList 컴포넌트 수정
  src/components/MenuList/MenuList.tsx
Labels: 🐞 Bug

#124 웹 접근성 개선
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/Day/Day.tsx
  src/components/DateRangePicker/DateRangePicker.tsx
  src/components/ImageCarousel/ImageCarousel.tsx
  src/components/Label/Label.tsx
  src/components/MenuItem/MenuItem.tsx
  src/components/RadioButton/RadioButton.style.ts
  src/components/RadioButton/RadioButton.tsx
  src/components/Tab/Tab.tsx
  src/components/Tabs/Tabs.tsx
  src/components/Toggle/Toggle.tsx
  src/components/ToggleGroup/ToggleGroup.tsx
  src/stories/ImageCarousel.stories.tsx
  src/stories/Input.stories.tsx
Labels: 🔨 Refactor

#125 npm v1.2.2 배포
  README.md
  package-lock.json
  package.json
  src/utils/date.ts
Labels: 🌏 Environment

#126 웹 접근성 개선
  src/components/ImageCarousel/ImageCarousel.tsx
  src/components/ImageUploadInput/ImageUploadInput.tsx
  src/components/Label/Label.tsx
  src/components/StarRatingInput/StarRatingInput.tsx
Labels: 🔨 Refactor

#127 npm v1.2.3 배포
  package-lock.json
  package.json
Labels: 🌏 Environment

#128 npm v1.2.4 배포
  package-lock.json
  package.json
  src/components/ImageCarousel/ImageCarousel.tsx
Labels: 🐞 Bug, 🌏 Environment

#130 eslint 설정 수정 및 storybook a11y 애드온 추가
  .eslintrc.json
  .storybook/main.ts
  package-lock.json
  package.json
  src/HangLogProvider.tsx
  src/assets/index.d.ts
  src/components/Badge/Badge.tsx
  src/components/Box/Box.tsx
  src/components/Button/Button.tsx
  src/components/Calendar/Calendar.tsx
  src/components/Calendar/Day/Day.tsx
  src/components/Checkbox/Checkbox.tsx
  src/components/Flex/Flex.tsx
  src/components/FloatingButton/FloatingButton.tsx
  src/components/Heading/Heading.tsx
  src/components/ImageCarousel/ImageCarousel.tsx
  src/components/ImageUploadInput/ImageUploadInput.tsx
  src/components/Label/Label.tsx
  src/components/Menu/Menu.tsx
  src/components/MenuItem/MenuItem.tsx
  src/components/Modal/Modal.tsx
  src/components/RadioButton/RadioButton.tsx
  src/components/SVGCarousel/SVGCarousel.tsx
  src/components/Select/Select.style.ts
  src/components/Select/Select.tsx
  src/components/StarRatingInput/StarRatingInput.tsx
  src/components/Tab/Tab.tsx
  src/components/Text/Text.tsx
  src/components/Toast/Toast.tsx
  src/components/Toggle/Toggle.tsx
  src/components/ToggleGroup/ToggleGroup.tsx
  src/hooks/useImageCarousel.ts
  src/hooks/useStarRatingInput.ts
  src/stories/Badge.stories.tsx
  src/stories/Box.stories.tsx
  src/stories/Button.stories.tsx
  src/stories/Center.stories.tsx
  src/stories/Checkbox.stories.tsx
  src/stories/Day.stories.tsx
  src/stories/Divider.stories.tsx
  src/stories/Flex.stories.tsx
  src/stories/FloatingButton.stories.tsx
  src/stories/Heading.stories.tsx
  src/stories/Input.stories.tsx
  src/stories/RadioButton.stories.tsx
  src/stories/Select.stories.tsx
  src/stories/Skeleton.stories.tsx
  src/stories/Spinner.stories.ts
  src/stories/Text.stories.tsx
  src/stories/Textarea.stories.tsx
  src/stories/Toast.stories.tsx
  src/stories/ToggleGroup.stories.tsx
  src/utils/date.ts
Labels: 🌏 Environment, 🔨 Refactor

#131 npm v1.2.5 배포
  README.md
  package-lock.json
  package.json
Labels: 🌏 Environment

#132 npm v1.2.7 배포
  package-lock.json
  package.json
  src/components/ImageUploadInput/ImageUploadInput.style.ts
  src/components/ImageUploadInput/ImageUploadInput.tsx
  src/stories/ImageUploadInput.stories.tsx
Labels: 🐞 Bug, 🌏 Environment, 🔨 Refactor
