Repository hang-log-design-system/design-system, pull requests merged in 2023-08, with the labels that each got.

#133 npm v1.2.8 배포
  package-lock.json
  package.json
  src/components/Button/Button.tsx
Labels: 🐞 Bug, 🌏 Environment

#135 Toast 컴포넌트 수정
  src/components/Toast/Toast.style.ts
  src/components/Toast/Toast.tsx
Labels: 🔨 Refactor

#136 npm v1.2.9 배포
  README.md
  package-lock.json
  package.json
Labels: 🌏 Environment, 🔨 Refactor

#138 useOverlay 수정
  src/hooks/useOverlay.ts
  src/stories/Modal.stories.tsx
Labels: 🔨 Refactor

#139 npm v1.2.10 배포
  README.md
  package-lock.json
  package.json
Labels: 🔨 Refactor

#140 npm v1.2.11 배포
  README.md
  package-lock.json
  package.json
Labels: ✨ Feature

#142 StarRating 컴포넌트 재구축
  src/assets/svg/half-empty-left-star.svg
  src/assets/svg/half-empty-right-star.svg
  src/assets/svg/half-filled-left-star.svg
  src/assets/svg/half-filled-right-star.svg
  src/components/StarRatingInput/StarRatingInput.style.ts
  src/components/StarRatingInput/StarRatingInput.tsx
  src/hooks/useStarRatingInput.ts
  src/stories/StarRatingInput.stories.tsx
Labels: 🔨 Refactor, ✨ Feature

#145 useStarRatingInput onClick 인자만 롤백
  src/hooks/useStarRatingInput.ts
Labels: 🔨 Refactor

#148 StarRatingInput 깜빡임 이슈 수정
  src/components/StarRatingInput/StarRatingInput.style.ts
Labels: 🔨 Refactor

#149 npm v1.2.16 배포
  README.md
  package-lock.json
  package.json
Labels: ✨ Feature

#154 SVGCarouselModal 추가
  src/components/SVGCarouselModal/SVGCarouselModal.style.ts
  src/components/SVGCarouselModal/SVGCarouselModal.tsx
  src/index.tsx
  src/stories/SVGCarouselModal.stories.tsx
Labels: ✨ Feature

#155 npm v1.2.22 배포
  README.md
  package-lock.json
  package.json
Labels: ✨ Feature

#156 SVGCarousel boxStyling css 수정, dots Styling 수정
  src/components/SVGCarouselModal/SVGCarouselModal.style.ts
  src/components/SVGCarouselModal/SVGCarouselModal.tsx
  src/stories/SVGCarouselModal.stories.tsx
Labels: 🔨 Refactor

#157 npm v1.2.25 배포
  package-lock.json
  package.json
Labels: 🔨 Refactor

#158 SVGCarouselModal 버튼 갭, dots 갭 추가
  src/components/SVGCarouselModal/SVGCarouselModal.style.ts
  src/components/SVGCarouselModal/SVGCarouselModal.tsx
  src/stories/SVGCarouselModal.stories.tsx
Labels: ✨ Feature

#159 npm v1.3.0 배포
  README.md
  package-lock.json
  package.json
Labels: ✨ Feature
